### ISSUE TITLE
LogFormatter improvements

### ISSUE THREAD

**Issue by tburry** [vanilla/garden-cli#23]
The LogFormatter right now is hardcoded to php://output. I want to be able to specify another output stream or even multiple output destinations, some of which may not be a file stream (ex. database, syslog). The garden-cli won't be responsible for doing any of the work or wiring these up; it just needs to make useful classes available to libraries.

Any changes must be backwards compatible.

**Comment by cdepage** [comment]
"Done" criteria (after lengthy discussion with Todd & dePage):
- interface for "formatters" to implement
- stream writer
- collection writer
- PSR writer
