### ISSUE TITLE
Allow one to programatically trigger the help screen

### ISSUE THREAD

**Issue by bramus** [vanilla/garden-cli#3]
An extra (public) function `showHelp()` which triggers `writeHelp()` (with its proper arguments) would be nice to have.

**Comment by dpiquet** [comment]
I would also find it useful !

In fact i already changed Cli::writeHelp function from private to public so i can call it from my own code. Seems no other changes is required to make it work. I just have to load the appropriate schema using Cli::getSchema (which was already public) so i can give it back to the writeHelp function.

**Comment by bramus** [comment]
Awesome, thanks!
