### ISSUE TITLE
Logger has no fluid interface

### ISSUE THREAD

**Issue by CodeAndWeb** [vanilla/garden-cli#30]
This does not work as documented:

    $log = new TaskLogger();
    $log->info('This is a message.')
        ->error('This is an error.') // outputs in red

The `info()` method has return type void in the trait. It only works like this:

    $log = new TaskLogger();
    $log->info('This is a message.');
    $log->error('This is an error.');

**Comment by tburry** [comment]
Good point. I'd like the interface to be fluid, but I think PSR compliance is more important. The README has been updated here: https://github.com/vanilla/garden-cli/blob/master/README.md#example.
