### ISSUE TITLE
multiple arguments

### ISSUE THREAD

**Issue by rino1** [vanilla/garden-cli#40]
There is a way to make a parameter accept multiple arguments?
Example:
`
        $cli->arg(
            'SINGLE', 
            ''...,' 
            true
        );
        $cli->arg(
            'MULTIPLE', 
            ''...,' 
            true.
            true // multiple
        );
`
Usage:
`
$ mycopy source target1 target2 target3....
`

**Comment by simonLeary42** [comment]
@rino1 did you find that this feature already exists?

**Comment by simonLeary42** [comment]
I see that an option can have multiple values, but I don't see that for an argument.

**Comment by simonLeary42** [comment]
Partial workaround:

```php
<?php
include "./vendor/autoload.php";
use Garden\Cli\Cli;
$cli = new Cli();
$cli->opt("foo", "blah blah blah")->arg("bar", "blah blah blah");
$args = $cli->parse($argv);
echo json_encode(
    ["args_args" => array_values($args->getArgs()), "args_opts" => $args->getOpts()],
    JSON_PRETTY_PRINT
);
echo "\n";
```

```console
$ php test.php --foo=hello world world world
```

```json
{
    "args_args": [
        "world",
        "world",
        "world"
    ],
    "args_opts": {
        "foo": "hello"
    }
}
```

This couldn't work for `mycopy source target1 target2 target3`, since it treats all argument values as part of the same array. If I omit the `array_values`, I can see that the first `world` is bound to the `bar` argument and the others are dangling:
```json
{
    "args_args": {
        "bar": "world",
        "1": "world",
        "2": "world"
    },
    "args_opts": {
        "foo": "hello"
    }
}
```
