### ISSUE TITLE
Allow Format -o=value or --option=value

### ISSUE THREAD

**Issue by mastacheata** [vanilla/garden-cli#5]
This is more of a feature request than an actual issue, but still:

Please add an option to allow the equals symol to be used as a seperator for option name and value.
Right now you have no seperator at all or space (and thus a new element in argv) as a separator.
Having the = like the getopt from php does would be very welcome here.

Thanks in advance.

**Comment by tburry** [comment]
The CLI supports the equals sign for the long form arguments, but not the short form. That's a sensible request though.

**Comment by mastacheata** [comment]
Oh, apparently I only tried it with the short form.
Must have overlooked the fact that long form allows = as separator, even though I looked into the sourcecode just for that purpose...

Thanks for considering it, though.

**Comment by tburry** [comment]
Okay I added support for short = separators in 8d46ebb4e5cdc7f4c2d2b83101d0e46b9ad758da which goes out in version 1.3.0. I also added a few more unit tests for some edge cases,  but I may not have caught everything. If you have any issues open an issue and I'll fix.
