### ISSUE TITLE
Turn formatting on/off

### ISSUE THREAD

**Issue by mastacheata** [vanilla/garden-cli#6]
I've been trying the library on windows and that doesn't support the bold or colored items you have in there by default. It would be great if there was a way to turn that off without having to fiddle with the libraries code.

**Comment by tburry** [comment]
You can turn formatting off with the following code:

```php

$cli = new Cli();
$cli->format = false;
```

I look into a way of turning formatting off by default on Windows.

**Comment by tburry** [comment]
Can you tell me what the output of the following command is on your Windows terminal?

```php
echo shell_exec('tput colors 2> output');
```

**Comment by mastacheata** [comment]
On my computer it prints 8 and puts nothing in the file.
BUT: I have the Git / MingW64 tools (a bundle of common cli tools from *nix systems as windows exe files)
Even though it prints out the number and is available it can't overcome the limitation of Windows CMD no longer supporting ANSI escape sequences (no longer here means since the release of Windows 95, more than 20 years ago)

You're probably more interested in what SHOULD happen, and that is something along the lines of this command doesn't exist being printed to the output file.
My Widnows is set to German language, though, so this is what the output file contains:

    Der Befehl "tputs" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.

I can very well live with turning it off by hand, though...

**Comment by tburry** [comment]
Okay thanks for the info. I'm going to think about whether or not to add the default based solely on the OS being Windows. It sounds sensible, but then someone will come along with Cygwin.

**Comment by yakatz** [comment]
Windows 10 now supports colors in conhost, so it would be nice to revisit this.
